# Generated by Django 5.1 on 2024-08-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PseudoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('visa_status', models.CharField(choices=[('citizen', 'Citizen'), ('permanent_resident', 'Permanent Resident'), ('temporary_resident', 'Temporary Resident'), ('student', 'Student'), ('work_permit', 'Work Permit')], default='citizen', max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
