# Generated by Django 5.1 on 2024-08-09 00:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='technology',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
