# Generated by Django 5.1 on 2024-08-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0002_technology_created_at_technology_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
